---
title: "K-mean Clustering"
author: "Chang Shi"
date: "11/01/2023"
output:
  pdf_document: default
  html_document:
    df_print: paged
---








```{r}
library(tidyverse)
library(cluster)
```



```{r}
data <- read.csv("init_data.csv")

# Drop the first column (Unnamed: 0) as it appears to be an identifier
data <- data[,-1]

# Convert categorical variables to one-hot encoded format
data_encoded <- as.data.frame(model.matrix(~.-1, data))

```

```{r}
# Determine the optimal number of clusters using the elbow method
inertias <- c()
cluster_range <- 1:14  # Checking for up to 14 clusters

for (k in cluster_range) {
  set.seed(42)  # Setting seed for reproducibility
  kmeans_result <- kmeans(data_encoded, centers=k, nstart=25)
  inertias <- c(inertias, kmeans_result$tot.withinss)
}

# Plotting the elbow curve
plot(cluster_range, inertias, type="l", col="blue", xlab="Number of Clusters", ylab="Inertia",
     main="Elbow Method for Optimal Number of Clusters", ylim=c(min(inertias), max(inertias)))
points(cluster_range, inertias, pch=19, col="red")
grid(col="black")
```